<!DOCTYPE data-dictionary [
        <!ELEMENT data-dictionary (statement-execution-processor)*>
        <!ELEMENT statement-execution-processor (statement)*>
        <!ATTLIST statement-execution-processor
                id CDATA #REQUIRED
                is-query CDATA #IMPLIED>
        <!ELEMENT statement (#PCDATA)>
        <!ATTLIST statement
                comment CDATA #IMPLIED
                variants CDATA #IMPLIED>
        ]>
<data-dictionary>
    <statement-execution-processor id="create-view">
        <statement>create view {0} as {1}</statement>
    </statement-execution-processor>

    <statement-execution-processor id="change-view">
        <statement>create or replace view {0} as {1}</statement>
    </statement-execution-processor>





    <statement-execution-processor id="create-object">
        <statement>create {0}</statement>
    </statement-execution-processor>

    <statement-execution-processor id="change-object">
        <statement>create or replace {0}</statement>
    </statement-execution-processor>
    
    <statement-execution-processor id="drop-object">
        <statement>drop {0} {1}</statement>
    </statement-execution-processor>

    <statement-execution-processor id="drop-object-body">
        <statement>drop {0} body {1}</statement>
    </statement-execution-processor>

</data-dictionary>